hash-format = "sha256"

[[files]]
file = "_config.yml"
hash = "485e7574c4a5fcb8433e32d7bcaea2a0f0be2db482b06bba1abc7b8d6957221e"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "1cba40748219add171324904e2c4f19020ad6a03ecb3d24d45212e9f14475f6c"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "cf7c3b60dc1615f94a0c292242bef1b0c1953b495438ea1c9f5895a7169743fd"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "422472dc3d1783a706d23bddaa775bca5970392505c575b143195cccd57b3982"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "b2e81ade6286aadd3a7e3f0a32a7c122ea665fd3ff74c9d563f31f3d2a3e71d6"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "3b01094400618f74596b9a3d0a5b60082e67bbb75174b592cd1393905584a8a7"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "ae3ac32c7479293516b5e52b3fa2f75f850a19d5e00db836bb7238d3d3650a22"

[[files]]
file = "config/yosbr/options.txt"
hash = "64736dfe35a3fd4a97b435a82a14d81005e50510e911b0456b1e8b332829c2fc"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "fbad3ce2bcab1b8a73a541000100dc5ed3323bcf571e4e2a4a3c28db5c520509"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "242e18d68cb8d218df43e713e97239631f8612384789068659c4898cfa49fcef"
metafile = true

[[files]]
file = "mods/armor-chroma-for-fabric.pw.toml"
hash = "c5aed03f2fff1bc659f22a51590f70946474e038d878f2ff6f7ff41a954a9f8c"
metafile = true

[[files]]
file = "mods/better-biome-blend.pw.toml"
hash = "aeaefb6089a1cf7635b3722aabdda71baea6e0e72547ca3bb7726400ae5b93cd"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "e8cd685b609577ab23e2a55ec3273a1ff9475daef52f0999b2c5d27f7c795f5c"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "309fa9d0ab190059d9a13933db512f36f01ec0b40f37fa6e919ec085c686df9e"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "407fd025c6912135c7d40c238bb96fe05ea8172c403a100ed86f978fc8124c81"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "01ab4442937c2d1f582722d139c0d02b3fc36c61a3eeebb4e81bd5256b7d8470"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "c3c73a4ae07f1ab6de623b37007df3581286fe3495377af6d3da4b105892adb2"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "3648ed55ffae5bc153c16b2d414925cc30165b5171aa0e2a146e5ba22366fcf1"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "c06e098c6d6eda6da4492e4a8dff1796e6081bbd30f487ffb89e1ed3c485e805"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
hash = "4fb938b3b07afc32216c63ba982ba25e28f4d0e63ddecdd26bea4e6dfa77b0fc"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "783c0415795fc4bea6d85315aac54d3a3f2770fcd02d66dad1f626b311f8bf4f"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "81a389a5035dc0852ce12c796f1d667bb4715b1d6ffde16433bf80f02e3796bc"
metafile = true

[[files]]
file = "mods/entity-collision-fps-fix.pw.toml"
hash = "d614e471929c4906f85ba776600e0cfa9b0d958ce55121efd49c9ffd4ff00a04"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "2d6dd083a7b01b1035a52c09a088137b930ea6f0f8f28ae3e0ba23f05937e3ef"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "df12767833f6d916dcb6f6b9a75da6a1cbc134600561bc5588c3f0cbca03c93b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "0c7c2c37874d5341092e6c63f95f4f95d7fa804e1c28ea9e83c1ed5115dcf12f"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "3d195b45c6dff7ee5a52dcb9e57a4172c91ec8d5c9d17c97305ee674fc22a357"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "2ea587bc28af997f2b93de69af32b8ba0120ce8a2c0e95624a0c55051eb25041"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "0ab0925b9d00ddcf75dc5077fba4eee2c825945a7590750e1821ba783fb26f37"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8fb914c75a06a677721dd1fc880606d790886be9e0b392820dcecb9bb56e0786"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "d2a65b42dcefbda9ac5c170ff5bf59b4a56ba192993a13d0b0da9b1f0678b4b3"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "4716789e4a806c1cabcef27e67150215edb4c3d737e9a87d90f2f615d6c196cd"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4ff1e58c9c7fdce5cd5a392987c3013d02ce63ee2ed4149098389a85caac2838"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "1aa7510ec1a3994273a20f8b341f676583b9ede2eaea3badd46deb7178d92a6c"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "db4b9b11b1f59b156b3a56bf9a7ac7b5218f3c43fdc7d83d5c2963820a9ef88d"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "a2e4e7b3b072d44a518ac1313c88d6f3b17727d554f700d91c7b4eb3588de50c"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "04506b094026b5cb0e23636f4c60eb8e200d057ed6710e2b4cc615f7806aaded"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "1c6d01b013b9e8c6dd921046adc7c7768814c17a0fde45cbe695c8e2de40f8be"
metafile = true

[[files]]
file = "mods/smooth-boot.pw.toml"
hash = "eb68f07474889d53f9b81902ad7aca2979604aa6d5102327574b687b1e1c1424"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "e31f409ab01c4df8b9b678cb533722b852c38d1563f6ead0ef40f282b17c45ff"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "79870ab97caf526e6599d2d429ef778848935bbaf2c7020948e203afbb3f32bc"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "be68ef606c339bbb22f2b812db1e5264d9e3335befc0c348d4dc91a8a3e72e17"
metafile = true

[[files]]
file = "mods/statuseffecttimer.pw.toml"
hash = "1da5f38d24b00e49108dedf43fe3dd388bade82563e5f69689d051167ea57927"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "1d0adb6150edfe74a7a51ce4069d399330fdd920b4f4ad4dc39de7a588490f8e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "fe29fcc69744fa90f4fd35890cc44033d1b5bca0e0d45cb40c89250eabad6ab3"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "7c2712882baa2ed177b9b961cc1052b857f11ed1455609f9e9f01332c0317f12"
metafile = true
